Domain\Logging\Model\Workout:
  type: entity
  table: workouts
  repositoryClass: Domain\Logging\Infrastructure\Persistence\Doctrine\WorkoutRepository
  embedded:
    workoutId:
      class: Domain\Logging\Model\WorkoutId
  id:
        id:
          type: integer
          column: workout_id
          generator:
            strategy: AUTO
  fields:
    date:
      type: datetime
      column: workout_date