Domain\Logging\Model\Workout\Workout:
  type: entity
  table: workouts
  repositoryClass: Domain\Logging\Infrastructure\Persistence\Doctrine\WorkoutRepository
  embedded:
    workoutId:
      class: Domain\Logging\Model\Workout\WorkoutId
    time:
      class: Domain\Logging\Model\Workout\Time
  id:
        id:
          type: integer
          column: workout_id
          generator:
            strategy: AUTO