Domain\Logging\Model\ExerciseType\ExerciseType:
  type: entity
  table: exercise_types
  repositoryClass: Adapters\Persistence\Doctrine\Logging\ExerciseTypeRepository
  embedded:
    exerciseTypeId:
      class: Domain\Logging\Model\ExerciseType\ExerciseTypeId
  id:
    id:
      type: integer
      column: exercise_type_id
      generator:
        strategy: AUTO
  fields:
    name: {type: string}