Model\Workout:
  type: entity
  table: workouts
  id:
    id:
      type: integer
      column: workout_id
      generator:
        strategy: AUTO
  fields:
    date:
      type: datetime
      column: workout_date